# Generated by Django 5.0.6 on 2024-07-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=100)),
                ('program_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('available_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=100)),
                ('program_code', models.CharField(max_length=100)),
                ('exhibition_date', models.DateField()),
                ('program_start_time', models.TimeField()),
                ('average_audience', models.FloatField()),
            ],
        ),
    ]
